[06/04/23]: Scheduled job on mac.local

diff --git a/scripts/kforward b/scripts/kforward
--- a/scripts/kforward
+++ b/scripts/kforward
@@ -1,10 +1,31 @@
-#!/bin/sh
+#!/usr/bin/env zsh
+
+###############################################################################
+# kforward 1.0                                                                #
+# Altair Bueno MIT license                                                    #
+# https://github.com/Altair-Bueno/Demeter                                     #
+#                                                                             #
+# Port forwarding between localhost and Kubernetes services.                  #
+# Lists all services from all namespaces and allows the user to choose the    #
+# desired service to connect                                                  #
+###############################################################################
+
 set -e
 
-################################################################################
 # Args
 KUBE_FORWARD_PORT_RANGE="${1:-3000-32000}"
-KUBE_FORWARD_SEPARATOR="${2:-:}"
+KUBE_FORWARD_SEPARATOR="${2:-/}"
+
+if [[ "$KUBE_FORWARD_PORT_RANGE" =~ '[[:digit:]]+-[[:digit:]]+' ]] 
+then
+    KUBE_FORWARD_PORT="$(shuf -i "$KUBE_FORWARD_PORT_RANGE" -n 1)"
+elif [[ "$KUBE_FORWARD_PORT_RANGE" =~ '[[:digit:]]+' ]]
+then
+    KUBE_FORWARD_PORT="$KUBE_FORWARD_PORT_RANGE"
+else
+    echo "Invalid port range $KUBE_FORWARD_PORT_RANGE"
+    exit 1
+fi
 
 ################################################################################
 # Prompt for service
@@ -18,15 +39,11 @@ KUBE_SERVICE_NAME=$(cut "-d$KUBE_FORWARD_SEPARATOR" -f2 <<< "$KUBE_SERVICE")
 # Obtain service port
 KUBE_SERVICE_PORT="$(kubectl get "--namespace=$KUBE_SERVICE_NAMESPACE" "service/$KUBE_SERVICE_NAME" '-ojsonpath={.spec.ports[0].port}')"
 
-# Start port forwarding
-if [[ "$KUBE_FORWARD_PORT_RANGE" =~ '-' ]] 
-then
-    KUBE_FORWARD_PORT="$(shuf -i "$KUBE_FORWARD_PORT_RANGE" -n 1)"
-else    
-    KUBE_FORWARD_PORT="$KUBE_FORWARD_PORT_RANGE"
-fi
-
 echo "Starting port forwarding..."
 echo "http://localhost:$KUBE_FORWARD_PORT"
 echo "https://localhost:$KUBE_FORWARD_PORT"
-kubectl port-forward "--namespace=$KUBE_SERVICE_NAMESPACE" "service/$KUBE_SERVICE_NAME" "$KUBE_FORWARD_PORT:$KUBE_SERVICE_PORT"
+
+kubectl port-forward \
+    "--namespace=$KUBE_SERVICE_NAMESPACE" \
+    "service/$KUBE_SERVICE_NAME" \
+    "$KUBE_FORWARD_PORT:$KUBE_SERVICE_PORT"
